### ISSUE TITLE
How did you get this to work?

### ISSUE THREAD

**Issue by ghost** [dafn/svelte-typescript-rollup#5]
I tried to to this myself and failed. How did you figure out the right way to set up `rollup.config.js`? Does the order of the plugins matter?

**Comment by dafn** [comment]
try cloning the repo and run `yarn && yarn serve`. It should work

**Comment by ghost** [comment]
Naah, the template works for me. I mean, how did you originally set this up?

**Comment by dafn** [comment]
A good technique is to set up one plugin at a time and confirming it works before moving to the next one. The official [tutorial](https://rollupjs.org/guide/en/#tutorial) is very helpful in teaching how to set up rollup
